name: deploy-tickets

on:
  push:
    branches:
      - master
    paths:
      - 'tickets/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: cd tickets && docker build -t kevintlee01/tickets .
      - run: docker push kevintlee01/tickets
      
